dev: back to top navigation funtionality
ilemarandrade/landing-swordvoice-2.0 pull request #27
Opened 2024-01-25 18:53 UTC by chellysA

2024-01-25 21:27 UTC, Yireh2016 requested changes
Revisa tambien los conflictos. Buen trabajo.

2024-01-25 21:27 UTC, Yireh2016 commented on src/constants/Hooks/useBackToTopButton.tsx
> +    if (!showBackToTopButton && window.scrollY > 680) {
680 es una medida arbitraria. Creo que esto deberia depender de dos factores... si estas en PC y la medida vertical de la pantalla/monitor/ventana donde estes viendo la pagina.

2024-01-25 23:34 UTC, Yireh2016 commented
Aca tambien hay conflictos. Por favor resolver.

2024-01-26 02:02 UTC, chellysA commented on src/constants/Hooks/useBackToTopButton.tsx
> +    if (!showBackToTopButton && window.scrollY > 680) {
Buena corrección. Aprendi mucho!

2024-01-26 02:08 UTC, ilemarandrade approved these changes

2024-01-26 04:21 UTC, ilemarandrade commented on src/constants/Hooks/useBackToTopButton.tsx
> +    if (!showBackToTopButton && window.scrollY > 680) {
@Yireh2016  revisa y si todo esta ok has el merge

2024-01-27 17:39 UTC, Yireh2016 approved these changes

2024-01-27 17:39 UTC, merged