feat: add descriptions and enhance carousel
ilemarandrade/landing-swordvoice-2.0 pull request #28
Opened 2024-01-25 18:55 UTC by chellysA

2024-01-25 22:08 UTC, Yireh2016 requested changes

2024-01-25 22:08 UTC, Yireh2016 commented on src/constants/swordvoices.tsx
> +          "CEO, Consultor IT con 10+ años de experiencia, 5 años de desarrollo web moderno y gestión de equipos. Gran trabajador en entornos de equipo multiculturales.",
CEO, Consultor IT y negocios con 10+ años de experiencia, 8 años de desarrollo web moderno y gestión de equipos en entornos multiculturales.

2024-01-25 22:08 UTC, Yireh2016 commented on src/constants/swordvoices.tsx
> +        "Mentora, eficiente en el desarrollo de interfaces de usuarios, minusiosa y creativa en el diseño pixel to pixel y responsivo de apps.",
"pixel to pixel"

2024-01-25 22:09 UTC, Yireh2016 commented
should we do these reviews in english? That would be great for practicing too.

2024-01-25 22:10 UTC, Yireh2016 commented
Check merge conflicts ?

2024-01-25 23:32 UTC, Yireh2016 commented on src/app/page.tsx
> +      <div id="our_paths" className="h-auto xl:min-h-screen bg-white w-full ">
espacio de mas al final...pudieran usar un prettier/eslint para que automaticamente borre estos espacios al salvar los archivos.

2024-01-25 23:53 UTC, chellysA commented on src/constants/swordvoices.tsx
> +          "CEO, Consultor IT con 10+ años de experiencia, 5 años de desarrollo web moderno y gestión de equipos. Gran trabajador en entornos de equipo multiculturales.",
actualiza tu linkedlin jaja

2024-01-26 00:05 UTC, chellysA commented
> should we do these reviews in english? That would be great for practicing too.

yes, i should do the entire page in english, it is tomorrow task.

2024-01-26 00:29 UTC, Yireh2016 commented
> > should we do these reviews in english? That would be great for practicing too.
> 
> yes, i should do the entire page in english, it is tomorrow task.

Me refiero a los reviews

2024-01-26 00:30 UTC, Yireh2016 approved these changes

2024-01-26 00:35 UTC, ilemarandrade approved these changes

2024-01-26 00:35 UTC, merged